server:
  port: 8080
  secret_key: ######

task:
  cron_expr: 0 0 3 * * *

rss:
  config_url: "https://cdn.aimiliy.top/npm/json/RSS.json"
  output_file: "output/feed_result.json"


log:
  file: "output/crawl.log"
